#!/usr/bin/env ruby

require 'optparse'
begin
  require 'term/rgbcolor'
rescue LoadError
  module Term
    RGBColor = Struct.new(:r, :g, :b) { def to_s; ''; end }
  end
end

git_options = []

OptionParser.new do |parser|
  parser.separator "List last commits of all reachable git branches"
  parser.separator ""
  parser.separator "Options:"
  parser.on('-a', '--all', 'Show local and remote branches') do |time|
    git_options << '-a'
  end

end.parse!

SORT_BY='authordate'

# see https://git-scm.com/docs/git-for-each-ref#_field_names
FORMAT=[
  '%(objectname:short)',
  '%(refname:lstrip=2)',
  '%(subject)',
  '%(authorname)',
  '%(authoremail)',
  '%(authordate:iso8601)',
  '%(authordate:raw)',
]

reset   = "\e[0m"
yellow  = Term::RGBColor.new(175, 95, 0)
yellow  = "\e[33m" if yellow.to_s.empty?

branches = `git branch #{git_options.join(' ')} --format='#{FORMAT.join("\t")}' --sort #{SORT_BY}`.split("\n")

branch_length = branches.map {|b| b.split("\t")[1].length}.max
max_column_length = `tput cols`.to_i if true
branches.each {|branch|
  f = branch.split("\t")

  # prevent too dark commit hash colors
  r = f[0][0..1].to_i(16)*200/255 + 50
  g = f[0][2..3].to_i(16)*200/255 + 50
  b = f[0][4..5].to_i(16)*200/255 + 50
  color = Term::RGBColor.new(r, g, b).to_s
  color = "\e[3#{f[0].to_i(16)%7+1}m" if color.empty?

  # indicate age by grey colors
  age = Time.now.to_i - f[6].to_i

  staleness = [255 - Math::log(1+age/86400).ceil*12, 75].max
  age_color = Term::RGBColor.new(staleness, staleness, staleness)

  if $stdout.tty?
    message_length = max_column_length-1 - (f[0].size + 1 + 19 + 1 + branch_length + 1)
  else
    message_length = -1
    color = age_color = yellow = ''
  end

  output = [
    "#{color}#{f[0]}#{reset}",
    "#{age_color}#{f[5][0..18]}#{reset}",
    "#{yellow}#{f[1].ljust(branch_length)}#{reset}",
    f[2][0..message_length]
  ].join(' ')

  puts output
}
